import {
  AutocompletePlus,
  ButtonPlus,
  CascaderPlus,
  CascaderPanelPlus,
  CheckBoxPlus,
  ColorPickerPlus,
  CustomPlus,
  DatePickerPlus,
  DateTimePickerPlus,
  InputNumberPlus,
  InputPlus,
  RadioPlus,
  RatePlus,
  SelectPlus,
  SliderPlus,
  SuperCustomPlus,
  SwitchPlus,
  TimePickerPlus,
  TimeSelectrPlus,
  TransferPlus,
  UploadPlus,
} from '../modules'
const vnodes = {
  Autocomplete: AutocompletePlus,
  Button: ButtonPlus,
  Cascader: CascaderPlus,
  CascaderPanel: CascaderPanelPlus,
  CheckBox: CheckBoxPlus,
  ColorPicker: ColorPickerPlus,
  Custom: CustomPlus,
  DatePicker: DatePickerPlus,
  DateTimePicker: DateTimePickerPlus,
  InputNumber: InputNumberPlus,
  Input: InputPlus,
  Radio: RadioPlus,
  Rate: RatePlus,
  Select: SelectPlus,
  Slider: SliderPlus,
  Switch: SwitchPlus,
  TimePicker: TimePickerPlus,
  TimeSelect: TimeSelectrPlus,
  Transfer: TransferPlus,
  Upload: UploadPlus,
}

export const SuperCustom = SuperCustomPlus

export default vnodes
