import {
  CascaderPlus,
  CheckBoxPlus,
  ColorPickerPlus,
  DatePickerPlus,
  DateTimePickerPlus,
  InputNumberPlus,
  InputPlus,
  RadioPlus,
  RatePlus,
  SelectPlus,
  SliderPlus,
  SwitchPlus,
  TimePickerPlus,
  TransferPlus,
  UploadPlus,
} from '../modules'
const vnodes = {
  Cascader: CascaderPlus,
  CheckBox: CheckBoxPlus,
  ColorPicker: ColorPickerPlus,
  DatePicker: DatePickerPlus,
  DateTimePicker: DateTimePickerPlus,
  InputNumber: InputNumberPlus,
  Input: InputPlus,
  Radio: RadioPlus,
  Rate: RatePlus,
  Select: SelectPlus,
  Slider: SliderPlus,
  Switch: SwitchPlus,
  TimePicker: TimePickerPlus,
  Transfer: TransferPlus,
  Upload: UploadPlus,
}

export default vnodes
